const myProjects = [
    {
        name: "Random Quotes",
        description: "A random quote generator with Final Fantasy quotes.",
        info: "A random quote generator with Final Fantasy quotes. Made for FreeCodeCamp 'Front-End Libraries Certification'. It's function is simple, you can press a button called 'Change Quote' to get a new quote, or you can 'tweet it' with the 'twitter' button.",
        techUsed: ['fab fa-react', 'fab fa-js', 'fab fa-html5', 'fab fa-sass', 'fab fa-bootstrap'],
        projectImg: "/img/projects/random-quotes.png",
        slug: "random-quotes",
        externalUrl: "https://codepen.io/Lightark/full/eYpWowg",
    },
    {
        name: "Text Markdown",
        description: "A text markdown previewer, write text and it will be converter to html code.",
        info: "A text markdown previewer, write text and it will be converter to html code.",
        techUsed: ['fab fa-react', 'fab fa-js', 'fab fa-html5', 'fab fa-sass', 'fab fa-bootstrap'],
        projectImg: "/img/projects/markdown-preview.png",
        slug: "text-markdown",
        externalUrl: "https://codepen.io/Lightark/full/zYvzOKP",
    },
    {
        name: "Drum machine",
        description: "A Drum machine, let's compose some music!",
        info: "A Drum machine, let's compose some music!",
        techUsed: ['fab fa-react', 'fab fa-js', 'fab fa-html5', 'fab fa-sass', 'fab fa-bootstrap'],
        projectImg: "/img/projects/drum-machine.png",
        slug: "drum-machine",
        externalUrl: "https://codepen.io/Lightark/full/zYvzOKP",
    },
    {
        name: "Technical Documentation",
        description: "A single page with sidebar about JS",
        info: "A single page with sidebar about JS",
        techUsed: ['fab fa-html5', 'fab fa-css3-alt'],
        projectImg: "/img/projects/technical-documentation.png",
        slug: "technical-documentation",
        externalUrl: "https://codepen.io/Lightark/full/yLBzmOY",
    },
    {
        name: "Rep solar",
        description: "One of the projects I did during my IndianWebs' internship",
        info: "One of the projects I did during my IndianWebs' internship. (It can maybe change by the time you see this)",
        techUsed: ['fab fa-html5', 'fab fa-css3-alt', 'fab fa-wordpress'],
        projectImg: "/img/projects/rep-solar.png",
        slug: "rep-solar",
        externalUrl: "https://rep-solar.com/",
    },
    {
        name: "Survey Form",
        description: "A short form about some videogames...",
        info: "A short form about some videogames...",
        techUsed: ['fab fa-html5', 'fab fa-css3-alt'],
        projectImg: "/img/projects/survey-form.png",
        slug: "survey-form",
        externalUrl: "https://codepen.io/Lightark/full/RwbZqVQ",
    },
    {
        name: "My first Project",
        description: "A short project about my handsome boyfriend who teached.",
        info: "A short project about my handsome boyfriend who teached me about web development. Maybe that's why I really love web development?",
        techUsed: ['fab fa-html5', 'fab fa-css3-alt'],
        projectImg: "/img/projects/first-project.png",
        slug: "first-project",
        externalUrl: "./Pag2/hey.html",
    },
];

export default myProjects;